name: screenshot

on:
  workflow_dispatch:
    inputs:
      url:
        description: Target URL
        required: true
      request_id:
        description: Request ID
        required: true

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer

      - name: Debug inputs
        run: |
          echo "URL = '${{ inputs.url }}'"
          echo "REQUEST_ID = '${{ inputs.request_id }}'"

      - name: Run screenshot
        env:
          TARGET_URL: ${{ inputs.url }}
        run: node screenshot.js

      - name: Zip screenshot
        run: zip screenshot.zip screenshot.png

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-${{ inputs.request_id }}
          path: screenshot.zip
          retention-days: 1
